following from here: https://stackoverflow.com/a/50200350/7483950

In [11]:
import numpy as np
import torch
X = np.random.uniform(size=300)
Y = X + 0.25*X*np.random.normal(size=X.shape[0])

In [12]:
X.mean()

0.5060476503588354

In [14]:
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mean_coeff = torch.nn.Parameter(torch.Tensor([0]))
        self.var_coeff = torch.nn.Parameter(torch.Tensor([1]))

    def forward(self, x):
        return torch.distributions.Normal(self.mean_coeff * x, self.var_coeff * x)

mdl = Model()
optim = torch.optim.SGD(mdl.parameters(), lr=1e-3)

In [15]:
for _ in range(2000): # epochs
    dist = mdl(torch.from_numpy(X).float())
    obj = -dist.log_prob(torch.from_numpy(Y).float()).mean()
    optim.zero_grad()
    obj.backward()
    optim.step()

In [17]:
dist

Normal(loc: torch.Size([300]), scale: torch.Size([300]))

In [93]:
m = torch.distributions.Normal(torch.tensor([1]), torch.tensor([1.0]))

In [84]:
m = torch.distributions.Normal(torch.tensor([2]), torch.tensor([1.0]))

In [74]:
m.batch_shape

torch.Size([1])

In [106]:
x = torch.Tensor([-2, -1, -0.2, 0, 0.2, 0.5, 1, 2])+1
print(x)
print(torch.exp(m.log_prob(x)) / 0.4)
print(m.cdf(x))
print(m.icdf(x))

tensor([-1.0000,  0.0000,  0.8000,  1.0000,  1.2000,  1.5000,  2.0000,  3.0000])
tensor([0.1350, 0.6049, 0.9776, 0.9974, 0.9776, 0.8802, 0.6049, 0.1350])
tensor([0.0228, 0.1587, 0.4207, 0.5000, 0.5793, 0.6915, 0.8413, 0.9772])
tensor([   nan,   -inf, 1.8416,    inf,    nan,    nan,    nan,    nan])


In [104]:
math.e

2.718281828459045

In [98]:
import math
math.log(10)

2.302585092994046

In [101]:
math.log(100)

4.605170185988092

In [81]:
m = torch.distributions.Normal(torch.tensor([[0.0],[1],[2]]), torch.tensor([[1.0],[1],[1]]))
m

Normal(loc: torch.Size([3, 1]), scale: torch.Size([3, 1]))

In [83]:
x = torch.Tensor([-0.2, 0, 0.5])
print(x)
m.cdf(x)

tensor([-0.2000,  0.0000,  0.5000])


tensor([[0.4207, 0.5000, 0.6915],
        [0.1151, 0.1587, 0.3085],
        [0.0139, 0.0228, 0.0668]])

In [82]:
x = torch.Tensor([[-0.2],[0],[0.5]])
print(x)
m.cdf(x)

tensor([[-0.2000],
        [ 0.0000],
        [ 0.5000]])


tensor([[0.4207],
        [0.1587],
        [0.0668]])

In [ ]:
# x = torch.Tensor([[-0.2, 0, 0.5],[-0.2, 0, 0.5],[-0.2, 0, 0.5]])

In [22]:
m.sample()

tensor([0.8911])

In [16]:
print(mdl.mean_coeff, mdl.var_coeff)
# tensor(1.0150) tensor(0.2597)

Parameter containing:
tensor([0.9805], requires_grad=True) Parameter containing:
tensor([0.2401], requires_grad=True)


In [56]:
import torch
print (torch.__version__)

_ = torch.random.manual_seed (2021)

N = 2
C = 3
H = 5
W = 7

probs = torch.randn (N, C, H, W).softmax (1)
# print ('probs = ...')
# print (probs)
# # print ('probs.sum (1) = ...')
# # print (probs.sum (1))
# print(probs.transpose(1, -1))

sample = torch.distributions.Categorical (probs = probs.transpose (1, -1)).sample().transpose (-1, -2).unsqueeze (1)

print ('sample.shape =', sample.shape)
print ('sample = ...')
print (sample)

1.13.1.post200
probs = ...
tensor([[[[0.1498, 0.3152, 0.2946, 0.6541, 0.3106, 0.4475, 0.3918],
          [0.1289, 0.2494, 0.5813, 0.1555, 0.2688, 0.1649, 0.6196],
          [0.1607, 0.7599, 0.2339, 0.3343, 0.6459, 0.7187, 0.5310],
          [0.2014, 0.0938, 0.2341, 0.8172, 0.3617, 0.0953, 0.6246],
          [0.8510, 0.1427, 0.0091, 0.1163, 0.2765, 0.6657, 0.2254]],

         [[0.7174, 0.1177, 0.1747, 0.1609, 0.3015, 0.0444, 0.2602],
          [0.1545, 0.5129, 0.2338, 0.4810, 0.2133, 0.6208, 0.1486],
          [0.3673, 0.0383, 0.2041, 0.4826, 0.0756, 0.1309, 0.2405],
          [0.4219, 0.5621, 0.0419, 0.0825, 0.4854, 0.4959, 0.0707],
          [0.1043, 0.7390, 0.1671, 0.5642, 0.5226, 0.3112, 0.3942]],

         [[0.1329, 0.5671, 0.5306, 0.1850, 0.3879, 0.5082, 0.3480],
          [0.7167, 0.2377, 0.1849, 0.3635, 0.5179, 0.2143, 0.2318],
          [0.4720, 0.2018, 0.5620, 0.1831, 0.2785, 0.1503, 0.2285],
          [0.3767, 0.3441, 0.7239, 0.1003, 0.1529, 0.4088, 0.3047],
          [0.0447

In [62]:
import torch
print (torch.__version__)

_ = torch.random.manual_seed (2021)

N = 2
C = 3
H = 5
W = 7

probs = torch.randn (N, C, H, W).softmax (1)
# print ('probs = ...')
# print (probs)
# # print ('probs.sum (1) = ...')
# # print (probs.sum (1))
# print(probs.transpose(1, -1))

sample = torch.distributions.Categorical(probs = probs.transpose (1, -1)).sample()#.transpose (-1, -2).unsqueeze (1)

print ('sample.shape =', sample.shape)
print ('sample = ...')
print (sample)

1.13.1.post200
sample.shape = torch.Size([2, 7, 5])
sample = ...
tensor([[[1, 1, 2, 1, 0],
         [0, 0, 0, 1, 1],
         [2, 2, 0, 0, 2],
         [0, 2, 0, 0, 2],
         [0, 2, 0, 1, 1],
         [0, 1, 0, 2, 0],
         [2, 2, 0, 0, 1]],

        [[0, 0, 2, 2, 1],
         [2, 1, 2, 2, 1],
         [1, 0, 0, 0, 2],
         [1, 2, 0, 2, 2],
         [1, 0, 1, 1, 0],
         [1, 0, 2, 0, 0],
         [1, 1, 2, 0, 2]]])
